#!/bin/zsh

# IDを配列として保存
IPCS_S=(`ipcs -s | cut -f2 -d" " | grep -o '[0-9]*'`)
IPCS_M=(`ipcs -m | cut -f2 -d" " | grep -o '[0-9]*'`)
IPCS_Q=(`ipcs -q | cut -f2 -d" " | grep -o '[0-9]*'`)

# メモリ、セマフォ、キューを消去
for id in $IPCS_M;
do
  ipcrm -m $id;
done

for id in $IPCS_S;
do
  ipcrm -s $id;
done

for id in $IPCS_Q;
do
  ipcrm -q $id;
done
