#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Specify one file name, with one argument."
    exit 1
fi

# make cppfile
touch $1.cpp

# set snippet
echo "include <bits/stdc++.h>" >> $1.cpp
echo "using namespace std;" >> $1.cpp
echo "" >> $1.cpp
echo "int main() {" >> $1.cpp
echo "" >> $1.cpp
echo "" >> $1.cpp
echo "  return 0;" >> $1.cpp
echo "}" >> $1.cpp
