#!/bin/sh

# argument is nothing
if [ $# = 0 ]; then
    echo "Specify file names as arguments."
    exit 1
fi

# repeat for argument 
for arg in $@
do
    if test -e "$arg.go"; then # Do not create $arg.go if it exists
    echo "$arg.go already exists."
    else
    touch $arg.go # make gofile
    echo "package main
    
    import (
        "bufio"
        "fmt"
        "os"
        "strconv"
    )

    var sc = bufio.NewScanner(os.Stdin)
    var wtr = bufio.NewWriter(os.Stdout)

    func nextInt() int {
	    sc.Scan()
	    i, e := strconv.Atoi(sc.Text())
	    if e != nil {
			panic(e)
	    }
	    return i
    }

    func nextLine() string {
	    sc.Scan()
	    return sc.Text()
    }

    func main() {
        //sc.Split(bufio.ScanWords)
        
    }
    "  > $arg.go
    fi
done
